defmodule Skloni.Tests.Skloni do
  @moduledoc false

  def tasks do
    [
      {"skloni", 1, "{1} Lep[] fant[] pride[].", "ednina, moški spol, imenovalnik"},
      {"skloni", 2, "{1} Lep[a] prijatelic[a] pride[].", "ednina, ženski spol, imenovalnik"},
      {"skloni", 3, "{1} Ljubljana to je zelo lep[o] mest[o].",
       "ednina, srednji spol, imenovalnik"},
      {"skloni", 4, "{2} Lep[a] fant[a] pride[ta].", "dvojina, moški spol, imenovalnik"},
      {"skloni", 5, "{2} Lep[i] prijatelic[i] pride[ta].", "dvojina, ženski spol, imenovalnik"},
      {"skloni", 6, "{2} Lep[i] stanovanj[i] kupi[ta].", "dvojina, srednji spol, imenovalnik"},
      {"skloni", 7, "{3} Lep[i] fant[i] pride[jo].", "množina, moški spol, imenovalnik"},
      {"skloni", 8, "{3} Lep[e] prijatelic[e] pride[jo].", "množina, ženski spol, imenovalnik"},
      {"skloni", 9, "{3} Lep[a] mest[a] pride[jo].", "množina, srednji spol, imenovalnik"},
      {"skloni", 10, "{1} Brez dobr[ega] fant[a] ni dneva.", "ednina, moški spol, rodilnik"},
      {"skloni", 11, "{1} Brez dobr[e] prijatelic[e] ni dneva.", "ednina, ženski spol, rodilnik"},
      {"skloni", 12, "{1} Brez dobr[ega] mest[eta] ni dneva.", "ednina, srednji spol, rodilnik"},
      {"skloni", 13, "{2} Brez dobr[ih] fant[ov] ni večera.", "dvojina, moški spol, rodilnik"},
      {"skloni", 14, "{2} Brez dobr[ih] prijatelic[] ni večera.",
       "dvojina, ženski spol, rodilnik"},
      {"skloni", 15, "{2} Brez dobr[ih] mest[] ni večera.", "dvojina, srednji spol, rodilnik"},
      {"skloni", 16, "{3} Brez dobr[ih] fant[ov] ni dneva.", "množina, moški spol, rodilnik"},
      {"skloni", 17, "{3} Brez dobr[ih] prijatelic[] ni dneva.",
       "množina, ženski spol, rodilnik"},
      {"skloni", 18, "{3} Brez dobr[ih] mest[] ni dneva.", "množina, srednji spol, rodilnik"},
      {"skloni", 19, "{1} K dobr[emu] fant[u] grem.", "ednina, moški spol, dajalnik"},
      {"skloni", 20, "{1} K dobr[i] prijatelic[i] grem.", "ednina, ženski spol, dajalnik"},
      {"skloni", 21, "{1} K dobr[emu] mest[u] grem.", "ednina, srednji spol, dajalnik"},
      {"skloni", 22, "{2} K dobr[ima] fant[oma] greva.", "dvojina, moški spol, dajalnik"},
      {"skloni", 23, "{2} K dobr[ima] prijatelic[ama] greva.", "dvojina, ženski spol, dajalnik"},
      {"skloni", 24, "{2} K dobr[ima] mest[oma] greva.", "dvojina, srednji spol, dajalnik"},
      {"skloni", 25, "{3} K dobr[im] fant[om] gremo.", "množina, moški spol, dajalnik"},
      {"skloni", 26, "{3} K dobr[im] prijatelic[am] gremo.", "množina, ženski spol, dajalnik"},
      {"skloni", 27, "{3} K dobr[im] mest[om] gremo.", "množina, srednji spol, dajalnik"},
      {"skloni", 28, "{1} Vidim dobr[ega] fant[a].", "ednina, moški spol, tožilnik"},
      {"skloni", 29, "{1} Vidim dobr[o] prijatelic[o].", "ednina, ženski spol, tožilnik"},
      {"skloni", 30, "{1} Vidim dobr[o] mest[o].", "ednina, srednji spol, tožilnik"},
      {"skloni", 31, "{2} Vidiva dobr[a] fant[a].", "dvojina, moški spol, tožilnik"},
      {"skloni", 32, "{2} Vidiva dobr[i] prijatelic[i].", "dvojina, ženski spol, tožilnik"},
      {"skloni", 33, "{2} Vidiva dobr[i] mest[i].", "dvojina, srednji spol, tožilnik"},
      {"skloni", 34, "{3} Vidimo dobr[e] fant[e].", "množina, moški spol, tožilnik"},
      {"skloni", 35, "{3} Vidimo dobr[e] prijatelic[e].", "množina, ženski spol, tožilnik"},
      {"skloni", 36, "{3} Vidimo dobr[a] mest[a].", "množina, srednji spol, tožilnik"},
      {"skloni", 37, "{1} O dobr[em] fant[u] govorim.", "ednina, moški spol, mestnik"},
      {"skloni", 38, "{1} O dobr[i] prijatelic[i] govorim.", "ednina, ženski spol, mestnik"},
      {"skloni", 39, "{1} O dobr[em] mest[u] govorim.", "ednina, srednji spol, mestnik"},
      {"skloni", 40, "{2} O dobr[ih] fant[ih] govoriva.", "dvojina, moški spol, mestnik"},
      {"skloni", 41, "{2} O dobr[ih] prijatelic[ah] govoriva.", "dvojina, ženski spol, mestnik"},
      {"skloni", 42, "{2} O dobr[ih] mest[ih] govoriva.", "dvojina, srednji spol, mestnik"},
      {"skloni", 43, "{3} O dobr[ih] fant[ih] govorimo.", "množina, moški spol, mestnik"},
      {"skloni", 44, "{3} O dobr[ih] prijatelic[ah] govorimo.", "množina, ženski spol, mestnik"},
      {"skloni", 45, "{3} O dobr[ih] mest[ih] govorimo.", "množina, srednji spol, mestnik"},
      {"skloni", 46, "{1} Z dobr[im] fant[om] grem.", "ednina, moški spol, orodnik"},
      {"skloni", 47, "{1} Z dobr[o] prijatelic[o] grem.", "ednina, ženski spol, orodnik"},
      {"skloni", 48, "{1} Z dobr[im] občutj[em] grem.", "ednina, srednji spol, orodnik"},
      {"skloni", 49, "{2} Z dobr[ima] fant[oma] greva.", "dvojina, moški spol, orodnik"},
      {"skloni", 50, "{2} Z dobr[ima] prijatelic[ama] greva.", "dvojina, ženski spol, orodnik"},
      {"skloni", 51, "{2} Z dobr[ima] orodj[ema] greva.", "dvojina, srednji spol, orodnik"},
      {"skloni", 52, "{3} Z dobr[imi] fant[i] gremo.", "množina, moški spol, orodnik"},
      {"skloni", 53, "{3} Z dobr[imi] prijatelic[ami] gremo.", "množina, ženski spol, orodnik"},
      {"skloni", 54, "{3} Z dobr[imi] orodj[i] gremo.", "množina, srednji spol, orodnik"}
    ]
  end
end
